image: markhobson/maven-chrome

stages:
  - test

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

test:
  stage: test
  allow_failure: true

  script:
    - mvn $MAVEN_OPTS clean package
    - mvn compile test
  artifacts:
    when: always
    name: 'report'
    expire_in: 1 h
    paths:
      - target/surefire-reports/*